<?php

namespace Jevisla\AlerteBundle\Repository;

/**
 * AlerteSkillRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
