<?php

namespace Jevisla\AlerteBundle\Repository;

/**
 * ImageAlerteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAlerteRepository extends \Doctrine\ORM\EntityRepository
{
}
