<?php

namespace Jevisla\MapBundle\Repository;

/**
 * FicheUserGoogleMapRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheUserGoogleMapRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvatarVoisins($id)
    {
        return $this->createQueryBuilder('a')
            ->where('a.idUser = :id')                      // Date de modification antérieure à :date
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
