<?php

namespace Jevisla\EvtsCulturelsBundle\Repository;

/**
 * CommuneRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommune($com, $limit)
    {
        $com = $com.'%';
        $qb = $this->createQueryBuilder('a');
        $qb->andWhere('a.nom LIKE :com')
            ->setParameter('com', $com);

        // Puis on ne retourne que $limit résultats
        $qb->setMaxResults($limit);
        $qb->orderBy('a.nom', 'ASC');
        // Enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getCommuneSelect($nom, $dept)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->andWhere('a.nom = :nom')
            ->andWhere('a.nomDept = :dept')
            ->setParameter('nom', $nom)
            ->setParameter('dept', $dept);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
