<?php

namespace Jevisla\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function myFind()
    {
        $qb = $this->createQueryBuilder('i');

        // On peut ajouter ce qu'on veut avant
        $qb
        ->where('i.id = :id');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getUserImage($id)
    {
        return $this->createQueryBuilder('i')
            ->where('i.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
