services:
#    jevisla_general.example:
#        class: Jevisla\GeneralBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  jevisla_general.imageNav:
      class: Jevisla\GeneralBundle\ImageNav\ImageNav
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"

  jevisla_general.twig.imageNav_extension:
      class: Jevisla\GeneralBundle\Twig\ImageNavExtension
      arguments:
          - "@jevisla_general.imageNav"
      tags:
          -  { name: twig.extension }  
     
  jevisla_general.imageUser:
      class: Jevisla\GeneralBundle\ImageUser\ImageUser
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"

  jevisla_general.twig.imageUser_extension:
      class: Jevisla\GeneralBundle\Twig\ImageUserExtension
      arguments:
          - "@jevisla_general.imageUser"
      tags:
          -  { name: twig.extension }
          
  jevisla_general.Avatar:
      class: Jevisla\GeneralBundle\ImageAvatar\ImageAvatar
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"

  jevisla_general.twig.imageAvatar_extension:
      class: Jevisla\GeneralBundle\Twig\ImageAvatarExtension
      arguments:
          - "@jevisla_general.Avatar"
      tags:
          -  { name: twig.extension }        
          
  jevisla_general.regexDate:
      class: Jevisla\GeneralBundle\RegexDate\RegexDate
          
  jevisla_general.twig.regexDate_extension:
      class: Jevisla\GeneralBundle\Twig\RegexDateExtension
      arguments:
          - "@jevisla_general.regexDate"
      tags:
          -  { name: twig.extension }
          
  jevisla_general.textTraitement:
      class: Jevisla\GeneralBundle\TextTraitement\TextTroncation  
      
  jevisla_general.beta.html_adder:
      class: Jevisla\GeneralBundle\Beta\BetaHTMLAdder
    
  jevisla_general.beta.listener:
      class: Jevisla\GeneralBundle\Beta\BetaListener
      arguments:
          - "@jevisla_general.beta.html_adder"
          - "2019-06-01"   
      tags:
          - { name: kernel.event_listener, event: kernel.response, method: processBeta }  
      
  jevisla_general.handler.session_idle:
      class: Jevisla\GeneralBundle\SessionTime\SessionIdleHandler
      arguments: 
          - "@session"
          - "@security.token_storage"
          - "@router"
          - "%session_max_idle_time%" 
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }    
          
          
  jevisla_general.pseudoUser:
      class: Jevisla\GeneralBundle\PseudoUser\PseudoUser
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"

  jevisla_general.twig.pseudoUser_extension:
      class: Jevisla\GeneralBundle\Twig\PseudoUserExtension
      arguments:
          - "@jevisla_general.pseudoUser"
      tags:
          -  { name: twig.extension }           